git-all: add error summary at end

diff --git a/git-all b/git-all
--- a/git-all
+++ b/git-all
@@ -24,16 +24,35 @@ else
     find_cmd="find \"$CODE_ROOT_DIR\" -type d -name .git ! -path '*/_*'"
 fi
 
-cmd=$1
+# The first argument must be a git command
+cmd="$1"
 shift
-
 [[ -z "$cmd" ]] && usage "No git command specified"
 
+# Change the pipe behaviour to allow modifying vars in a subshell (https://github.com/koalaman/shellcheck/wiki/SC2031)
+shopt -s lastpipe
+
 # Iterate through all known repositories
+declare -a err_repos=()
 eval $find_cmd |
     xargs dirname |
-    while read dir; do
+    while read -r dir; do
         log "Running ${CLR_OK}git $cmd${CLR_OFF} in $(dirname "$dir")/${CLR_VAR}$(basename "$dir")${CLR_OFF}"
-        git -C "$dir" $cmd "$@" || error "git returned non-zero exit code $?"
+        if ! git -C "$dir" "$cmd" "$@"; then
+            error "git returned non-zero exit code $?"
+            err_repos+=("$dir")
+        fi
         log '--------------------------------------------------------------------------------'
     done
+
+# If there was any failure, output a list of failed repositories
+if ((${#err_repos[@]})); then
+    echo
+    error "Failed in the following repos:"
+    for dir in "${err_repos[@]}"; do
+        dir="$(realpath --relative-to="$PWD" "$dir")"
+        echo -e "* $(dirname "$dir")/${CLR_VAR}$(basename "$dir")${CLR_OFF}"
+    done
+else
+    ok "Succeeded"
+fi
