Add usage() to common.sh; use library functions from common.sh

diff --git a/picasa-upload b/picasa-upload
--- a/picasa-upload
+++ b/picasa-upload
@@ -12,57 +12,15 @@
 #     album_name  - name of the destination Picasa album
 #=======================================================================================================================
 
+. "$(dirname "$(realpath "$0")")/common.sh"
+
 # Setup vars
 pic_size=1600                                                      # Max size of the pictures to upload
 file_watermark_white="$HOME/Pictures/Misc/dk-watermark-white.png"  # Default watermark file
 file_watermark_black="$HOME/Pictures/Misc/dk-watermark-black.png"  # Black watermark file
 file_watermark_small="$HOME/Pictures/Misc/dk-watermark-small.png"  # 'Small' watermark file
 picasa_owner="dmitry.kann"                                         # Owner of the Picasa account
-
-#-----------------------------------------------------------------------------------------------------------------------
-# Functions
-#-----------------------------------------------------------------------------------------------------------------------
-
-# Prints out a status message (overwritten every time)
-# Parameters:
-#   1 - message text
-status() {
-  # Pad/truncate the line to fit screen width
-  printf "%-${tty_width}.${tty_width}s\r" "$1"
-}
-
-# Prints out a progress message
-# Parameters:
-#   1 - current item number
-#   2 - total number of items
-#   3 - message text
-progress() {
-  printf -v msg '[%d/%d] %s' "$1" "$2" "$3"
-  status "$msg"
-}
-
-# Prints out a warning message
-# Parameters:
-#   1 - message
-warn() {
-  echo "WARNING: $1" >&2
-}
-
-# Prints out a failure message and exits
-# Parameters:
-#   1 - message
-err() {
-  echo "ERROR: $1" >&2
-  exit 1
-}
-
-# Displays usage info and exits
-# Parameters:
-#   1 - error message (if any)
-usage() {
-  [ -z "$1" ] || echo "ERROR: $1" >&2
-  cat << EOF >&2
-Usage: $0 [options] photos_dir album_name
+USAGE_INFO="Usage: $0 [options] photos_dir album_name
 Options:
   -B  Do not add a black border to the image
   -D  Do not delete the processed photos after uploading (leave them in the source dir)
@@ -73,19 +31,38 @@ Options:
   -d  Delete original (after successful processing)
   -s  Use "small" watermark instead of the default one (better for small images)
 
-album_name is mandatory unless -U is specified.
-EOF
-  exit 2
+album_name is mandatory unless -U is specified."
+
+#-----------------------------------------------------------------------------------------------------------------------
+# Functions
+#-----------------------------------------------------------------------------------------------------------------------
+
+# Prints out a status message (overwritten every time)
+# Arguments:
+#   $1 message text
+status() {
+    # Pad/truncate the line to fit screen width
+    printf "%-${tty_width}.${tty_width}s\r" "$1"
+}
+
+# Prints out a progress message
+# Arguments:
+#   $1 current item number
+#   $2 total number of items
+#   $3 message text
+progress() {
+    printf -v msg '[%d/%d] %s' "$1" "$2" "$3"
+    status "$msg"
 }
 
 # Fetches image details using its metadata. Return success/error code
-# Parameters:
-#   1 - image file name
+# Arguments:
+#   $1 image file name
 fetch_image_details() {
-  # Fetch image size
-  img_size=$(identify -quiet -format "%w %h" "$1" | awk '{print ($1>$2 ? $1 : $2)}') || warn "Determining image size in $1 failed."
-  # Fetch image caption (dataset 2, property 105, see http://www.imagemagick.org/script/escape.php for details)
-  img_caption=$(identify -quiet -format "%[IPTC:2:105]" "$1") || warn "Determining image caption in $1 failed."
+    # Fetch image size
+    img_size=$(identify -quiet -format "%w %h" "$1" | awk '{print ($1>$2 ? $1 : $2)}') || warn "Determining image size in $1 failed."
+    # Fetch image caption (dataset 2, property 105, see http://www.imagemagick.org/script/escape.php for details)
+    img_caption=$(identify -quiet -format "%[IPTC:2:105]" "$1") || warn "Determining image caption in $1 failed."
 }
 
 #=======================================================================================================================
@@ -109,45 +86,45 @@ args=$(getopt -o BDRUWbds -- "$@")
 [ $? -ne 0 ] && usage
 eval set -- $args
 for i; do
-  case "$i" in
-    -B)
-      unset s_border_options
-      shift
-      ;;
-    -D)
-      b_delete_processed=0
-      shift
-      ;;
-    -R)
-      b_resize=0
-      shift
-      ;;
-    -U)
-      b_delete_processed=0
-      b_upload=0
-      shift
-      ;;
-    -W)
-      b_watermark=0
-      shift
-      ;;
-    -b)
-      s_watermark_to_use="$file_watermark_black"
-      shift
-      ;;
-    -d)
-      b_delete_original=1
-      shift
-      ;;
-    -s)
-      s_watermark_to_use="$file_watermark_small"
-      shift
-      ;;
-    --)
-      shift;
-      break
-      ;;
-  esac
+    case "$i" in
+        -B)
+            unset s_border_options
+            shift
+            ;;
+        -D)
+            b_delete_processed=0
+            shift
+            ;;
+        -R)
+            b_resize=0
+            shift
+            ;;
+        -U)
+            b_delete_processed=0
+            b_upload=0
+            shift
+            ;;
+        -W)
+            b_watermark=0
+            shift
+            ;;
+        -b)
+            s_watermark_to_use="$file_watermark_black"
+            shift
+            ;;
+        -d)
+            b_delete_original=1
+            shift
+            ;;
+        -s)
+            s_watermark_to_use="$file_watermark_small"
+            shift
+            ;;
+        --)
+            shift;
+            break
+            ;;
+    esac
 done
 
 # Parse the rest of the command line
@@ -155,11 +132,11 @@ dir_photos="$1"
 picasa_album_name="$2"
 
 # Check photos_dir
-[ ! -z "$dir_photos" ] || usage "Directory for photos is not specified"
-[ -d "$dir_photos" ]   || err "Directory '$dir_photos' does not exist."
+[[ -n "$dir_photos" ]] || usage "Directory for photos is not specified"
+[[ -d "$dir_photos" ]] || err "Directory '$dir_photos' does not exist."
 
 # Check album_name
-[ $b_upload -eq 0 ] || [ ! -z "$picasa_album_name" ] || usage "Album name is not specified"
+[[ $b_upload -eq 0 ]] || [[ -n "$picasa_album_name" ]] || usage "Album name is not specified"
 
 #-----------------------------------------------------------------------------------------------------------------------
 # Initialization
@@ -167,7 +144,7 @@ picasa_album_name="$2"
 
 # Create a temp output dir if needed
 unset temp_dir
-[ $b_delete_processed -eq 0 ] || temp_dir=$(mktemp -d)
+[[ $b_delete_processed -eq 0 ]] || temp_dir=$(mktemp -d)
 
 # Get TTY width
 tty_width=$(stty size | cut -d ' ' -f 2)
@@ -196,56 +173,56 @@ i_count=${#files[@]}
 i_cur_num=0
 i_err_count=0
 for (( i_cur_num=1; i_cur_num<=${i_count}; i_cur_num++ )); do
-  src_file=${files[$((i_cur_num-1))]}
-  b_error=0
+    src_file=${files[$((i_cur_num-1))]}
+    b_error=0
 
-  # Determine output dir
-  if [ ! -z "$temp_dir" ]; then
-    output_dir="$temp_dir"
-  else
-    output_dir=$(dirname "$src_file")
-  fi
-
-  # Determine full output file name
-  src_file_name=$(basename "$src_file")
-  dst_file="$output_dir/${src_file_name%\.*}.picasaweb.$(echo ${src_file##*.} | tr '[:upper:]' '[:lower:]')"
-
-  # Print out status message
-  progress $i_cur_num $i_count "Processing $src_file"
-
-  # Try to fetch image details
-  fetch_image_details "$src_file"
-
-  # Determine the need for resize. We resize unless it's turned off, and only if picture size is unknown or bigger than
-  # the standard size
-  unset s_resize_flags
-  [ $b_resize -ne 0 ] && ( [ -z "$img_size" ] || [ $img_size -gt $pic_size ] ) && s_resize_flags="-resize $pic_size"
-
-  # Resize and autorotate the image, add a border if needed
-  if ! convert $s_resize_flags -quiet -quality 90 -auto-orient $s_border_options "$src_file" "$dst_file"; then
-    b_error=1
-    warn "Conversion of $src_file failed."
-  # Apply watermark
-  elif ! ( [ $b_watermark -eq 0 ] || composite -blend 90% -gravity southeast "$s_watermark_to_use" "$dst_file" "$dst_file" ); then
-    b_error=1
-    warn "Watermarking $src_file failed."
-  # Upload the picture
-  elif [ $b_upload -ne 0 ]; then
-    progress $i_cur_num $i_count "Uploading $dst_file";
-    if ! google picasa post "$picasa_album_name" "$dst_file" --owner "$picasa_owner" --summary "$img_caption" --quiet; then
-      b_error=1
-      warn "Uploading $dst_file failed."
+    # Determine output dir
+    if [[ -n "$temp_dir" ]]; then
+        output_dir="$temp_dir"
+    else
+        output_dir=$(dirname "$src_file")
     fi
-  fi
-  # If processing failed, add the picture to the failure list
-  if [ $b_error -ne 0 ]; then
-    failed_pics[$i_err_count]="$src_file"
-    ((i_err_count++))
-  fi
-  # If successfully processed, delete the original if needed
-  [ $b_error -eq 0 ] && [ $b_delete_original -ne 0 ] && ( rm -f "$src_file" || warn "Couldn't delete $src_file" )
-  # Remove the failed/handled picture if needed
-  ( [ $b_error -eq 0 ] && [ $b_delete_processed -eq 0 ] ) || [ ! -f "$dst_file" ] || rm -f "$dst_file"
+
+    # Determine full output file name
+    src_file_name=$(basename "$src_file")
+    dst_file="$output_dir/${src_file_name%\.*}.picasaweb.$(echo ${src_file##*.} | tr '[:upper:]' '[:lower:]')"
+
+    # Print out status message
+    progress $i_cur_num $i_count "Processing $src_file"
+
+    # Try to fetch image details
+    fetch_image_details "$src_file"
+
+    # Determine the need for resize. We resize unless it's turned off, and only if picture size is unknown or bigger than
+    # the standard size
+    unset s_resize_flags
+    [[ $b_resize -ne 0 ]] && ( [[ -z "$img_size" ]] || [[ $img_size -gt $pic_size ]] ) && s_resize_flags="-resize $pic_size"
+
+    # Resize and autorotate the image, add a border if needed
+    if ! convert $s_resize_flags -quiet -quality 90 -auto-orient $s_border_options "$src_file" "$dst_file"; then
+        b_error=1
+        warn "Conversion of $src_file failed."
+        # Apply watermark
+    elif ! ( [[ $b_watermark -eq 0 ]] || composite -blend 90% -gravity southeast "$s_watermark_to_use" "$dst_file" "$dst_file" ); then
+        b_error=1
+        warn "Watermarking $src_file failed."
+        # Upload the picture
+    elif [ $b_upload -ne 0 ]; then
+        progress $i_cur_num $i_count "Uploading $dst_file";
+        if ! google picasa post "$picasa_album_name" "$dst_file" --owner "$picasa_owner" --summary "$img_caption" --quiet; then
+            b_error=1
+            warn "Uploading $dst_file failed."
+        fi
+    fi
+    # If processing failed, add the picture to the failure list
+    if [[ $b_error -ne 0 ]]; then
+        failed_pics[$i_err_count]="$src_file"
+        ((i_err_count++))
+    fi
+    # If successfully processed, delete the original if needed
+    [[ $b_error -eq 0 ]] && [ $b_delete_original -ne 0 ] && ( rm -f "$src_file" || warn "Couldn't delete $src_file" )
+    # Remove the failed/handled picture if needed
+    ( [[ $b_error -eq 0 ]] && [[ $b_delete_processed -eq 0 ]] ) || [[ ! -f "$dst_file" ]] || rm -f "$dst_file"
 done
 
 #-----------------------------------------------------------------------------------------------------------------------
@@ -256,14 +233,13 @@ status "Done. $i_count files processed."
 echo
 
 # Remove temp dir if needed
-[ -z "$temp_dir" ] || rmdir --ignore-fail-on-non-empty "$temp_dir"
+[[ -z "$temp_dir" ]] || rmdir --ignore-fail-on-non-empty "$temp_dir"
 
 # Print out failure list if there's any
-if [ $i_err_count -gt 0 ]; then
-  warn "Processing of the following $i_err_count picture(s) failed:"
-  for f in ${failed_pics[@]}; do echo "$f" >&2; done
-  exit 1
+if [[ $i_err_count -gt 0 ]]; then
+    warn "Processing of the following $i_err_count picture(s) failed:"
+    for f in ${failed_pics[@]}; do echo "$f" >&2; done
+    exit 1
 fi
 
 exit 0
-
diff --git a/shotwell-thumbs b/shotwell-thumbs
--- a/shotwell-thumbs
+++ b/shotwell-thumbs
@@ -10,28 +10,12 @@
 #   Public domain
 #=======================================================================================================================
 
+. "$(dirname "$(realpath "$0")")/common.sh"
+
 # Setup vars
 DB_FILE="$HOME/.local/share/shotwell/data/photo.db"
 THUMB_BASE_DIR="$HOME/.cache/shotwell/thumbs/"
-
-# Get TTY width
-tty_width=$(stty size | cut -d ' ' -f 2)
-
-#-----------------------------------------------------------------------------------------------------------------------
-
-# Handles Ctrl-C
-interrupted() {
-  echo "Processing interrupted" >&2
-  exit 10
-}
-
-# Displays usage info and exits
-# Arguments:
-#   1 - optional error message
-usage() {
-  [[ -n "$1" ]] && echo "ERROR: $1" >&2
-  cat << EOF >&2
-Script for (re)generating Shotwell thumbnails. Written by Dmitry Kann, http://yktoo.com/
+USAGE_INFO="Script for (re)generating Shotwell thumbnails. Written by Dmitry Kann, http://yktoo.com/
 
 Usage: $0 [options]
 
@@ -41,65 +25,56 @@ Options:
   -128  Generate 128x128 thumbnail
   -360  Generate 360x360 thumbnail
 
-If neither -128 nor -360 is given, both sizes are generated.
+If neither -128 nor -360 is given, both sizes are generated."
 
-EOF
-  exit 1
-}
-
-# Logs a failure message and exits
-# Arguments:
-#   1 - message
-err() {
-  echo "ERROR: $1" >&2
-  exit 2
-}
+# Get TTY width
+tty_width=$(stty size | cut -d ' ' -f 2)
 
 # Prints out a status message (overwritten every time)
 # Arguments:
-#   1 - message text
+#   $1 message text
 status() {
-  # Pad/truncate the line to fit screen width
-  printf "%-${tty_width}.${tty_width}s\r" "$1"
+    # Pad/truncate the line to fit screen width
+    printf "%-${tty_width}.${tty_width}s\r" "$1"
 }
 
 # Prints out a progress message
 # Arguments:
-#   1 - current item number
-#   2 - total number of items
-#   3 - message text
+#   $1 current item number
+#   $2 total number of items
+#   $3 message text
 progress() {
-  printf -v msg '[%d/%d] %s' "$1" "$2" "$3"
-  status "$msg"
+    printf -v msg '[%d/%d] %s' "$1" "$2" "$3"
+    status "$msg"
 }
 
 # Generates a thumbnail file
 # Arguments:
-#   1 - thumbnail size, either 128 or 360
-#   2 - photo ID
-#   3 - photo file name
-#   4 - number of current photo
-#   5 - total number of photos
+#   $1 thumbnail size, either 128 or 360
+#   $2 photo ID
+#   $3 photo file name
+#   $4 number of current photo
+#   $5 total number of photos
 # Returns:
 #   Nonzero value if thumbnail generation was skipped
 generate_thumb() {
-  size="$1"
-  id="$2"
-  pic_file="$3"
-  thumb_file=$(printf "$THUMB_BASE_DIR/thumbs${size}/thumb%016x.jpg" "$id")
-  # If force regenerate or thumb file doesn't exist yet
-  if ((regenerate != 0)) || [[ ! -f "$thumb_file" ]]; then
-    progress "$4" "$5" "Generating $size thumbnail for $pic_file"
-    convert "$pic_file" -auto-orient -thumbnail "${size}x${size}" "$thumb_file"
-    if (($? != 0)); then
-      status ""
-      err "Generating thumbnail for $pic_file failed"
+    size="$1"
+    id="$2"
+    pic_file="$3"
+    thumb_file=$(printf "$THUMB_BASE_DIR/thumbs${size}/thumb%016x.jpg" "$id")
+    # If force regenerate or thumb file doesn't exist yet
+    if ((regenerate != 0)) || [[ ! -f "$thumb_file" ]]; then
+        progress "$4" "$5" "Generating $size thumbnail for $pic_file"
+        convert "$pic_file" -auto-orient -thumbnail "${size}x${size}" "$thumb_file"
+        if (($? != 0)); then
+            status ""
+            err "Generating thumbnail for $pic_file failed"
+        fi
+        return 0
+    else
+        progress "$4" "$5" "Skipping $size thumbnail for $pic_file"
+        return 1
     fi
-    return 0
-  else
-    progress "$4" "$5" "Skipping $size thumbnail for $pic_file"
-    return 1
-  fi
 }
 
 #-----------------------------------------------------------------------------------------------------------------------
@@ -119,32 +94,32 @@ regenerate=0
 thumb128=
 thumb360=
 for arg; do
-  case "$arg" in
-    -h)
-      usage
-      ;;
+    case "$arg" in
+        -h)
+            usage
+            ;;
 
-    -r)
-      regenerate=1
-      ;;
+        -r)
+            regenerate=1
+            ;;
 
-    -128)
-      thumb128=1
-      ;;
+        -128)
+            thumb128=1
+            ;;
 
-    -360)
-      thumb360=1
-      ;;
+        -360)
+            thumb360=1
+            ;;
 
-    *)
-      usage "Unknown option: '$arg'"
-  esac
+        *)
+            usage "Unknown option: '$arg'"
+    esac
 done
 
 # If no size explicitly specified, activate both of them
 if [[ -z "$thumb128" ]] && [[ -z "$thumb360" ]]; then
-  thumb128=1
-  thumb360=1
+    thumb128=1
+    thumb360=1
 fi
 
 # Get the total number of photos
@@ -155,10 +130,10 @@ count_total=$(sqlite3 "$DB_FILE" "select count(*) from PhotoTable")
 count_cur=0
 count_done=0
 sqlite3 "$DB_FILE" "select id||' '||filename from PhotoTable order by timestamp desc" |
-  while read pic_id pic_file; do
-    ((thumb128 != 0)) && generate_thumb 128 "$pic_id" "$pic_file" "$((++count_cur))" "$count_total" && ((count_done++))
-    ((thumb360 != 0)) && generate_thumb 360 "$pic_id" "$pic_file" "$((++count_cur))" "$count_total" && ((count_done++))
-  done
+    while read pic_id pic_file; do
+        ((thumb128 != 0)) && generate_thumb 128 "$pic_id" "$pic_file" "$((++count_cur))" "$count_total" && ((count_done++))
+        ((thumb360 != 0)) && generate_thumb 360 "$pic_id" "$pic_file" "$((++count_cur))" "$count_total" && ((count_done++))
+    done
 
 echo
 status "Done. $count_total thumbnails processed, $count_done thumbnails generated"
