Added -d and -t options to override default timings.

diff --git a/y-generate-wallpaper-xml b/y-generate-wallpaper-xml
--- a/y-generate-wallpaper-xml
+++ b/y-generate-wallpaper-xml
@@ -11,8 +11,8 @@
 #=======================================================================================================================
 
 # Setup vars
-duration_static=1795
-duration_transition=5
+def_duration_static=1795
+def_duration_transition=5
 
 #-----------------------------------------------------------------------------------------------------------------------
 # Functions
@@ -21,17 +21,23 @@ duration_transition=5
 #-----------------------------------------------------------------------------------------------------------------------
 # Displays usage info and exits
 # Parameters:
-#   none
+#   1 - optional error message
 usage() {
+  [ ! -z "$1" ] && echo "ERROR: $1" >&2
   cat << EOF >&2
+XML wallpaper list generation script. Written by Dmitry Kann, http://yktoo.com/
+
 Usage: $0 [options] pictures_dir xml_file
 
 Options:
+  -d <number> Override default display duration ($def_duration_static seconds)
   -s <mode>   Sort the files according to <mode>, whose values are:
      name     Sort by file path and name
      shuffle  Randomize file order
+  -t <number> Override default transition duration ($def_duration_transition
+              seconds). If 0, no transition is used
   -v          Verbose output
-  -w          Set the freshly generated XML file as current wallpaper
+  -w          Set the generated XML file as current wallpaper
 
 pictures_dir  Path to directory with pictures
 
@@ -53,15 +59,21 @@ err() {
 #-----------------------------------------------------------------------------------------------------------------------
 
 # Parse the command line
+typeset -i duration_static=$def_duration_static
+typeset -i duration_transition=$def_duration_transition
 b_set_wallpaper=0
 b_verbose=0
 sort_command='cat'
 
-args=$(getopt -o s:vw -- "$@")
+args=$(getopt -o d:s:t:vw -- "$@")
 [ $? -eq 0 ] || usage
 eval set -- $args
 for i; do
   case "$i" in
+    -d)
+      duration_static=$2
+      [ "$duration_static" -le 0 ] && usage "Display duration should be greater than zero"
+      ;;
     -s)
       case $2 in
         name)
@@ -71,10 +83,13 @@ for i; do
           sort_command="shuf"
           ;;
         *)
-          echo "Invalid sort mode: $2"
-          usage
+          usage "Invalid sort mode: $2"
           ;;
       esac
+      ;;
+    -t)
+      [ -z "$2" ] && usage "Transition duration not specified"
+      duration_transition=$2
       ;;
     -v)
       b_verbose=1
@@ -96,6 +111,12 @@ file_output_xml="$2"
 [ ! -z "$dir_wallpapers"  ] || usage
 [ -d "$dir_wallpapers"    ] || err "Directory $dir_wallpapers does not exist"
 [ ! -z "$file_output_xml" ] || usage
+
+# Verbose output
+[ $b_verbose -ne 0 ] && (
+  echo "Display duration: $duration_static sec"
+  echo "Transition duration: $duration_transition sec"
+)
 
 # Canonicalize directory and output file name (make it absolute)
 dir_wallpapers=$(readlink -f $dir_wallpapers)
@@ -120,7 +141,7 @@ unset last_img_file
 i_count=0
 while read img_file; do
   # Insert transition statement if it's not the first image
-  if [ ! -z "$last_img_file" ]; then
+  if [[ ! -z "$last_img_file" && "$duration_transition" -gt 0 ]]; then
     cat << EOF >>"$file_output_xml"
 <transition>
   <duration>$duration_transition</duration>
